### PR TITLE
custom logger

### PR DESCRIPTION
**Pull request by Pfeifenjoy**
Allow users to pass a custom logging function for warnings.

### CODE REVIEW

**Comment by alexmarqs** [comment]
Thanks for submitting your PR, I will have a look later today! 🙏

**Comment by Pfeifenjoy** [comment]
Hi @alexmarqs

sounds cool, I am of course good with it.
Actually I tried this out in an application I am building now and noticed that it actually is not the right idea.
Usually someone would configure the log level in the config, which is after the adapter is executed.

I am thinking about changing this a bit because my intention was to have the adapters fail silently. That can also be done by leaving the warn log function empty but I am not sure if that is a good approach or if it is better to add the option "silent" to the adapters. Let me know of your opinion.

**Comment by alexmarqs** [comment]
Hi @Pfeifenjoy , actually why not both 🤔 ? Last night drafted something about your suggestion, see PR changes.(introduced a silentFail for the adapters, maybe we could also have a generic/config level that would apply this setting for all adapters, but I think having it per adapter should be fine for now).

 Cheers, let me know your feedback!

**Comment by alexmarqs** [comment]
I will merge this later today as I think it introduces some small cool features to next release, thanks for the contribution. In the meantime let me know if this fits your use case or if you would like to see any other! If so, feel free to open a new issue or reach me out. Thanks.

**Review by alexmarqs — APPROVED** [review]

**Comment by alexmarqs** [comment]
Released [here](https://github.com/alexmarqs/zod-config/releases/tag/v0.0.3). As usual, feel free to share any other suggestions or requests in a new issue. tks!

**Pull request merged**
